### ISSUE TITLE
如何修改背景颜色

### ISSUE THREAD

**Issue by chenpan1996** [Tomotoes/hexo-theme-tomotoes#1]
您好，请问一下如何修改背景颜色呢

**Comment by SimonAKing** [comment]
打开source/css/_partial/variable.less，找到以 **@bg- 开头**的代码 ，其中 **@bg-main** 代表的就是背景颜色，
因为我设置的是渐变背景，所以你可以有两种选择。
#### 1.  继续使用渐变背景，
就要把 所有的颜色都修改，也就是下面的 #F5F1F1  rgb(239, 241, 243) 这些
```css
@bg-main:linear-gradient(180deg, #F5F1F1 30%, rgb(239, 241, 243) 45%, rgb(247, 244, 238) 71%, #EFEFEF 91%);

```
可以去[这个网站](http://gradient.awesomes.cn/)进行修改，然后把修改结果 粘贴复制替换即可。

#### 2. 不想使用渐变背景，
就打开同路径下的layout.less 
```css
#main {
    padding-left: @menuWidth;
    min-height: 100%;
    .transition(.4s);
    background-image: @bg-main;
}
```
**将 ` background-image: @bg-main;`去掉，换成 background-color：xxx**
